### ISSUE TITLE
Speedtest

### ISSUE THREAD

**Issue by nitzel** [nitzel/cellularcoverage#7]
- [x] Speedtest working
- [x] Geolocation working
- [x] Upload data to the database
  - [x] Security/Validity checks (server-side)

**Comment by MrIngelborn** [comment]
Not sure on how we are going to do the quality function. Going to add validations on the server-side to make sure the data is correct 
Done in later commit 4c0814b485110a6e5cd9848109a0e2d39c19a614

**Comment by nitzel** [comment]
related commit 4c0814b485110a6e5cd9848109a0e2d39c19a614
